# server 配置
server:
  port: 7070
  max-http-header-size: 10240
  servlet:
    context-path: /manager

# spring 配置
spring:
  application:
    name: spring-meeting-vue
  profiles:
    active: dev
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss.SSS
#    locale: zh_CN
#    serialization:
#      # 格式化输出
#      indent_output: false

